spring.application.name=SpringBoot_Learning
server.port=8085 
spring.data.mongodb.uri=mongodb+srv://sameerrehan714_db_user:sameer49394@springbootlearning.qwnx8bi.mongodb.net/notes
#spring.data.mongodb.database=springboot_learning_db

spring.security.user.password=test 