spring.application.name=SpringBoot_Learning
server.port=8086 
spring.data.mongodb.uri=${MONGODB_CONNECTION_STRING}

#spring.data.mongodb.database=springboot_learning_db
jwt.secret=${JWT_SECRET_BASE64}
spring.security.user.password=test 